# More documentation about how to customize your build
# can be found here:
# https://docs.fastlane.tools
fastlane_version "2.68.0"

default_platform :android

# Fastfile actions accept additional configuration, but
# don't worry, fastlane will prompt you for required
# info which you can add here later
lane :beta do
  # build the release variant
   gradle(
      task: 'clean bundle',
      flavor: "prod",
      build_type: 'Release',
      properties: {
          "android.injected.signing.store.file" => "path-to-keystore",
          "android.injected.signing.store.password" => "",
          "android.injected.signing.key.alias" => "",
          "android.injected.signing.key.password" => "",
        }
    )

upload_to_play_store(track: 'beta',
                     package_name:'com.siju.acexplorer')
  # upload to HockeyApp
  #hockey(
  #  api_token: "023a6d8c6a474cc1883958696399973b"
  #)
end
