# More documentation about how to customize your build
# can be found here:
# https://docs.fastlane.tools
fastlane_version "2.68.0"

# This value helps us track success metrics for Fastfiles
# we automatically generate. Feel free to remove this line
# once you get things running smoothly!
generated_fastfile_id "68e78da0-8b2e-4e04-8c99-04758b33a4fd"

default_platform :android

# Fastfile actions accept additional configuration, but
# don't worry, fastlane will prompt you for required
# info which you can add here later
lane :beta do
  # build the release variant
   gradle(
      task: 'assemble',
      flavor: "prod",
      build_type: 'Release',
      properties: {
          "android.injected.signing.store.file" => "path-to-keystore",
          "android.injected.signing.store.password" => "",
          "android.injected.signing.key.alias" => "",
          "android.injected.signing.key.password" => "",
        }
    )

  # upload to HockeyApp
  hockey(
    api_token: "023a6d8c6a474cc1883958696399973b"
  )
end
