name: Android Build and Deployment Pipeline

on: [pull_request, push]

jobs:
  build:
    name: Setup Environment and build
    runs-on: ubuntu-latest
    env:
      KEYSTORE: ${{ secrets.KEYSTORE }}
      RELEASE_KEYSTORE_PATH: ${{ secrets.RELEASE_KEYSTORE_PATH }}
      KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
      KEY_ALIAS: ${{ secrets.KEYALIAS }}
      KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
            
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '22'
                
      - name: Setup Android SDK
        uses: android-actions/setup-android@v2
            
      - name: Make gradlew executable
        run: chmod +x ./gradlew
      
      - run: echo $RELEASE_KEYSTORE_PATH
      - run: touch $RELEASE_KEYSTORE_PATH
      - run: echo $KEYSTORE
      - run: echo "$KEYSTORE" | base64 -d > $RELEASE_KEYSTORE_PATH

      - run: cd app/
      - run: touch keystore.properties
      - run: echo -e "\nKEYSTORE_FILE=$RELEASE_KEYSTORE_PATH" >> keystore.properties
      - run: echo -e "\nKEYSTORE_PASSWORD=$KEYSTORE_PASSWORD" >> keystore.properties
      - run: echo -e "\nKEY_ALIAS=$KEY_ALIAS" >> keystore.properties
      - run: echo -e "\nKEY_PASSWORD=$KEY_PASSWORD" >> keystore.properties
      - run: cp key.jks app/

      - name: Generate app bundle
        run: ./gradlew app:bundleRelease --stacktrace

      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: Build Artifacts
          path: app/build/outputs/
