name: Android Build and Deployment Pipeline

on: [pull_request, push]

jobs:
  build:
    name: Setup Environment and build
    runs-on: ubuntu-latest
    env:
      KEYSTORE: ${{ secrets.KEYSTORE }}
      KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
      KEY_ALIAS: ${{ secrets.KEYALIAS }}
      KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
            
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
                
      - name: Setup Android SDK
        uses: android-actions/setup-android@v2
            
      - name: Make gradlew executable
        run: chmod +x ./gradlew
        
      - run: touch $RELEASE_KEYSTORE_PATH
      - run: echo $KEYSTORE | base64 --decode > $RELEASE_KEYSTORE_PATH
        
      - run: touch local.properties
      - run: echo -e "\nKEYSTORE_FILE=$RELEASE_KEYSTORE_PATH" >> local.properties
      - run: echo -e "\nKEYSTORE_PASSWORD=$KEYSTORE_PASSWORD" >> local.properties
      - run: echo -e "\nKEY_ALIAS=$KEY_ALIAS" >> local.properties
      - run: echo -e "\nKEY_PASSWORD=$KEY_PASSWORD" >> local.properties
      - run: cat local.properties 

      - name: Generate app bundle
        run: ./gradlew app:bundleRelease
       
          
#   STEP 2 : Upload the Artifact
  upload:
    needs: [ build ]
    name: Upload the signed artifact
    runs-on: ubuntu-latest
    steps:
      - name: Upload Bundle
        uses: actions/upload-artifact@v2
        with:
          name: signed_app_bundle
          path: app/build/outputs/bundle/release/app-release.aab
          
  
  
